
export const holpaMock = [
  {
    "id": 1,
    "classification": "성적,학업",
    "content": "최근 학교에서 스트레스를 많이 받아 힘듭니다. (사례 #1)",
    "createdAt": "2025.07.09",
    "recommends": 35,
    "reports": 7,
    "comments": 14,
    "severity": 2,
    "mindState": 1,
    "staeScore": 356,
    "sendLifeMessages": true
  },
  {
    "id": 2,
    "classification": "기타",
    "content": "외모에 대한 놀림이 있어 자존감이 떨어졌습니다. (사례 #2)",
    "createdAt": "2025.01.09",
    "recommends": 3,
    "reports": 2,
    "comments": 13,
    "severity": 2,
    "mindState": 5,
    "staeScore": 318,
    "sendLifeMessages": true
  },
  {
    "id": 3,
    "classification": "극복수기",
    "content": "부모님과의 대화가 자꾸 싸움으로 번져요. (사례 #3)",
    "createdAt": "2025.07.03",
    "recommends": 83,
    "reports": 13,
    "comments": 14,
    "severity": 4,
    "mindState": 5,
    "staeScore": 152,
    "sendLifeMessages": true
  },
  {
    "id": 4,
    "classification": "친구,이성",
    "content": "외모에 대한 놀림이 있어 자존감이 떨어졌습니다. (사례 #4)",
    "createdAt": "2025.03.29",
    "recommends": 35,
    "reports": 4,
    "comments": 13,
    "severity": 3,
    "mindState": 1,
    "staeScore": 57,
    "sendLifeMessages": false
  },
  {
    "id": 5,
    "classification": "성적,학업",
    "content": "용돈과 아르바이트 문제로 불안합니다. (사례 #5)",
    "createdAt": "2025.08.05",
    "recommends": 44,
    "reports": 8,
    "comments": 2,
    "severity": 4,
    "mindState": 5,
    "staeScore": 73,
    "sendLifeMessages": false
  },
  {
    "id": 6,
    "classification": "성적,학업",
    "content": "힘든 시기를 이겨냈던 경험을 나누고 싶습니다. (사례 #6)",
    "createdAt": "2025.03.17",
    "recommends": 106,
    "reports": 11,
    "comments": 36,
    "severity": 2,
    "mindState": 1,
    "staeScore": 33,
    "sendLifeMessages": true
  },
  {
    "id": 7,
    "classification": "선생갈등",
    "content": "수학 점수가 잘 오르지 않아 걱정이에요. (사례 #7)",
    "createdAt": "2025.08.07",
    "recommends": 29,
    "reports": 3,
    "comments": 24,
    "severity": 3,
    "mindState": 4,
    "staeScore": 335,
    "sendLifeMessages": false
  },
  {
    "id": 8,
    "classification": "친구,이성",
    "content": "용돈과 아르바이트 문제로 불안합니다. (사례 #8)",
    "createdAt": "2025.04.01",
    "recommends": 26,
    "reports": 8,
    "comments": 44,
    "severity": 1,
    "mindState": 5,
    "staeScore": 335,
    "sendLifeMessages": true
  },
  {
    "id": 9,
    "classification": "극복수기",
    "content": "부모님과의 대화가 자꾸 싸움으로 번져요. (사례 #9)",
    "createdAt": "2025.02.11",
    "recommends": 59,
    "reports": 12,
    "comments": 17,
    "severity": 5,
    "mindState": 2,
    "staeScore": 360,
    "sendLifeMessages": false
  },
  {
    "id": 10,
    "classification": "왕따,학폭",
    "content": "부모님과의 대화가 자꾸 싸움으로 번져요. (사례 #10)",
    "createdAt": "2025.07.30",
    "recommends": 4,
    "reports": 10,
    "comments": 25,
    "severity": 3,
    "mindState": 1,
    "staeScore": 118,
    "sendLifeMessages": false
  },
  {
    "id": 11,
    "classification": "부모갈등",
    "content": "밤마다 불면이 심해 일상에 지장이 있어요. (사례 #11)",
    "createdAt": "2025.04.12",
    "recommends": 113,
    "reports": 14,
    "comments": 9,
    "severity": 3,
    "mindState": 2,
    "staeScore": 136,
    "sendLifeMessages": false
  },
  {
    "id": 12,
    "classification": "기타",
    "content": "외모에 대한 놀림이 있어 자존감이 떨어졌습니다. (사례 #12)",
    "createdAt": "2025.08.18",
    "recommends": 74,
    "reports": 12,
    "comments": 23,
    "severity": 2,
    "mindState": 2,
    "staeScore": 270,
    "sendLifeMessages": false
  },
  {
    "id": 13,
    "classification": "성적,학업",
    "content": "최근 학교에서 스트레스를 많이 받아 힘듭니다. (사례 #13)",
    "createdAt": "2025.08.09",
    "recommends": 14,
    "reports": 4,
    "comments": 40,
    "severity": 2,
    "mindState": 4,
    "staeScore": 315,
    "sendLifeMessages": true
  },
  {
    "id": 14,
    "classification": "외모문제",
    "content": "외모에 대한 놀림이 있어 자존감이 떨어졌습니다. (사례 #14)",
    "createdAt": "2025.06.02",
    "recommends": 59,
    "reports": 8,
    "comments": 35,
    "severity": 1,
    "mindState": 1,
    "staeScore": 359,
    "sendLifeMessages": false
  },
  {
    "id": 15,
    "classification": "가정형편,경제",
    "content": "수학 점수가 잘 오르지 않아 걱정이에요. (사례 #15)",
    "createdAt": "2025.03.17",
    "recommends": 55,
    "reports": 5,
    "comments": 29,
    "severity": 1,
    "mindState": 3,
    "staeScore": 266,
    "sendLifeMessages": true
  },
  {
    "id": 16,
    "classification": "극복수기",
    "content": "수학 점수가 잘 오르지 않아 걱정이에요. (사례 #16)",
    "createdAt": "2025.08.11",
    "recommends": 80,
    "reports": 9,
    "comments": 40,
    "severity": 5,
    "mindState": 5,
    "staeScore": 111,
    "sendLifeMessages": true
  },
  {
    "id": 17,
    "classification": "가정형편,경제",
    "content": "친구와 사소한 오해로 사이가 멀어졌습니다. (사례 #17)",
    "createdAt": "2025.05.19",
    "recommends": 99,
    "reports": 0,
    "comments": 38,
    "severity": 3,
    "mindState": 4,
    "staeScore": 19,
    "sendLifeMessages": true
  },
  {
    "id": 18,
    "classification": "가정형편,경제",
    "content": "담임 선생님과의 관계가 어려워 상담이 필요합니다. (사례 #18)",
    "createdAt": "2025.03.03",
    "recommends": 7,
    "reports": 7,
    "comments": 36,
    "severity": 1,
    "mindState": 1,
    "staeScore": 384,
    "sendLifeMessages": false
  },
  {
    "id": 19,
    "classification": "성적,학업",
    "content": "힘든 시기를 이겨냈던 경험을 나누고 싶습니다. (사례 #19)",
    "createdAt": "2025.07.16",
    "recommends": 16,
    "reports": 4,
    "comments": 42,
    "severity": 4,
    "mindState": 5,
    "staeScore": 94,
    "sendLifeMessages": false
  },
  {
    "id": 20,
    "classification": "극복수기",
    "content": "어떤 선택을 해야 할지 조언이 필요합니다. (사례 #20)",
    "createdAt": "2025.04.19",
    "recommends": 27,
    "reports": 6,
    "comments": 45,
    "severity": 3,
    "mindState": 4,
    "staeScore": 353,
    "sendLifeMessages": false
  },
  {
    "id": 21,
    "classification": "캣츠아이",
    "content": "힘든 시기를 이겨냈던 경험을 나누고 싶습니다. (사례 #21)",
    "createdAt": "2025.04.26",
    "recommends": 15,
    "reports": 7,
    "comments": 14,
    "severity": 1,
    "mindState": 3,
    "staeScore": 20,
    "sendLifeMessages": true
  },
  {
    "id": 22,
    "classification": "기타",
    "content": "부모님과의 대화가 자꾸 싸움으로 번져요. (사례 #22)",
    "createdAt": "2025.01.02",
    "recommends": 9,
    "reports": 1,
    "comments": 14,
    "severity": 1,
    "mindState": 1,
    "staeScore": 450,
    "sendLifeMessages": false
  },
  {
    "id": 23,
    "classification": "성적,학업",
    "content": "힘든 시기를 이겨냈던 경험을 나누고 싶습니다. (사례 #23)",
    "createdAt": "2025.03.02",
    "recommends": 35,
    "reports": 15,
    "comments": 13,
    "severity": 5,
    "mindState": 2,
    "staeScore": 380,
    "sendLifeMessages": false
  },
  {
    "id": 24,
    "classification": "부모갈등",
    "content": "밤마다 불면이 심해 일상에 지장이 있어요. (사례 #24)",
    "createdAt": "2025.07.26",
    "recommends": 52,
    "reports": 6,
    "comments": 6,
    "severity": 1,
    "mindState": 4,
    "staeScore": 191,
    "sendLifeMessages": false
  },
  {
    "id": 25,
    "classification": "외모문제",
    "content": "밤마다 불면이 심해 일상에 지장이 있어요. (사례 #25)",
    "createdAt": "2025.08.10",
    "recommends": 93,
    "reports": 1,
    "comments": 43,
    "severity": 1,
    "mindState": 1,
    "staeScore": 216,
    "sendLifeMessages": false
  },
  {
    "id": 26,
    "classification": "성적,학업",
    "content": "부모님과의 대화가 자꾸 싸움으로 번져요. (사례 #26)",
    "createdAt": "2025.02.19",
    "recommends": 24,
    "reports": 14,
    "comments": 8,
    "severity": 4,
    "mindState": 2,
    "staeScore": 152,
    "sendLifeMessages": false
  },
  {
    "id": 27,
    "classification": "부모갈등",
    "content": "수학 점수가 잘 오르지 않아 걱정이에요. (사례 #27)",
    "createdAt": "2025.04.24",
    "recommends": 103,
    "reports": 3,
    "comments": 3,
    "severity": 5,
    "mindState": 1,
    "staeScore": 57,
    "sendLifeMessages": true
  },
  {
    "id": 28,
    "classification": "친구,이성",
    "content": "외모에 대한 놀림이 있어 자존감이 떨어졌습니다. (사례 #28)",
    "createdAt": "2025.05.05",
    "recommends": 61,
    "reports": 6,
    "comments": 25,
    "severity": 1,
    "mindState": 2,
    "staeScore": 204,
    "sendLifeMessages": true
  },
  {
    "id": 29,
    "classification": "외모문제",
    "content": "담임 선생님과의 관계가 어려워 상담이 필요합니다. (사례 #29)",
    "createdAt": "2025.08.26",
    "recommends": 100,
    "reports": 14,
    "comments": 18,
    "severity": 4,
    "mindState": 5,
    "staeScore": 348,
    "sendLifeMessages": false
  },
  {
    "id": 30,
    "classification": "친구,이성",
    "content": "부모님과의 대화가 자꾸 싸움으로 번져요. (사례 #30)",
    "createdAt": "2025.03.17",
    "recommends": 27,
    "reports": 1,
    "comments": 37,
    "severity": 5,
    "mindState": 1,
    "staeScore": 392,
    "sendLifeMessages": false
  },
  {
    "id": 31,
    "classification": "왕따,학폭",
    "content": "최근 학교에서 스트레스를 많이 받아 힘듭니다. (사례 #31)",
    "createdAt": "2025.05.30",
    "recommends": 61,
    "reports": 5,
    "comments": 3,
    "severity": 5,
    "mindState": 1,
    "staeScore": 445,
    "sendLifeMessages": true
  },
  {
    "id": 32,
    "classification": "성적,학업",
    "content": "어떤 선택을 해야 할지 조언이 필요합니다. (사례 #32)",
    "createdAt": "2025.01.18",
    "recommends": 86,
    "reports": 7,
    "comments": 25,
    "severity": 1,
    "mindState": 5,
    "staeScore": 136,
    "sendLifeMessages": true
  },
  {
    "id": 33,
    "classification": "기타",
    "content": "수학 점수가 잘 오르지 않아 걱정이에요. (사례 #33)",
    "createdAt": "2025.04.18",
    "recommends": 84,
    "reports": 10,
    "comments": 16,
    "severity": 2,
    "mindState": 3,
    "staeScore": 132,
    "sendLifeMessages": false
  },
  {
    "id": 34,
    "classification": "외모문제",
    "content": "친구와 사소한 오해로 사이가 멀어졌습니다. (사례 #34)",
    "createdAt": "2025.06.21",
    "recommends": 82,
    "reports": 9,
    "comments": 29,
    "severity": 3,
    "mindState": 1,
    "staeScore": 14,
    "sendLifeMessages": false
  },
  {
    "id": 35,
    "classification": "기타",
    "content": "어떤 선택을 해야 할지 조언이 필요합니다. (사례 #35)",
    "createdAt": "2025.01.26",
    "recommends": 9,
    "reports": 6,
    "comments": 32,
    "severity": 3,
    "mindState": 2,
    "staeScore": 487,
    "sendLifeMessages": false
  },
  {
    "id": 36,
    "classification": "성적,학업",
    "content": "부모님과의 대화가 자꾸 싸움으로 번져요. (사례 #36)",
    "createdAt": "2025.04.05",
    "recommends": 36,
    "reports": 5,
    "comments": 28,
    "severity": 5,
    "mindState": 3,
    "staeScore": 323,
    "sendLifeMessages": true
  },
  {
    "id": 37,
    "classification": "극복수기",
    "content": "담임 선생님과의 관계가 어려워 상담이 필요합니다. (사례 #37)",
    "createdAt": "2025.08.27",
    "recommends": 84,
    "reports": 3,
    "comments": 8,
    "severity": 3,
    "mindState": 1,
    "staeScore": 465,
    "sendLifeMessages": true
  },
  {
    "id": 38,
    "classification": "극복수기",
    "content": "친구와 사소한 오해로 사이가 멀어졌습니다. (사례 #38)",
    "createdAt": "2025.03.11",
    "recommends": 36,
    "reports": 6,
    "comments": 45,
    "severity": 3,
    "mindState": 2,
    "staeScore": 361,
    "sendLifeMessages": false
  },
  {
    "id": 39,
    "classification": "극복수기",
    "content": "밤마다 불면이 심해 일상에 지장이 있어요. (사례 #39)",
    "createdAt": "2025.03.06",
    "recommends": 115,
    "reports": 1,
    "comments": 5,
    "severity": 4,
    "mindState": 3,
    "staeScore": 32,
    "sendLifeMessages": true
  },
  {
    "id": 40,
    "classification": "가정형편,경제",
    "content": "친구와 사소한 오해로 사이가 멀어졌습니다. (사례 #40)",
    "createdAt": "2025.06.13",
    "recommends": 33,
    "reports": 5,
    "comments": 28,
    "severity": 5,
    "mindState": 4,
    "staeScore": 297,
    "sendLifeMessages": true
  },
  {
    "id": 41,
    "classification": "성적,학업",
    "content": "수학 점수가 잘 오르지 않아 걱정이에요. (사례 #41)",
    "createdAt": "2025.08.15",
    "recommends": 88,
    "reports": 4,
    "comments": 34,
    "severity": 1,
    "mindState": 3,
    "staeScore": 308,
    "sendLifeMessages": true
  },
  {
    "id": 42,
    "classification": "외모문제",
    "content": "친구와 사소한 오해로 사이가 멀어졌습니다. (사례 #42)",
    "createdAt": "2025.01.11",
    "recommends": 39,
    "reports": 11,
    "comments": 2,
    "severity": 3,
    "mindState": 2,
    "staeScore": 359,
    "sendLifeMessages": true
  },
  {
    "id": 43,
    "classification": "성적,학업",
    "content": "용돈과 아르바이트 문제로 불안합니다. (사례 #43)",
    "createdAt": "2025.07.19",
    "recommends": 71,
    "reports": 13,
    "comments": 39,
    "severity": 2,
    "mindState": 2,
    "staeScore": 452,
    "sendLifeMessages": true
  },
  {
    "id": 44,
    "classification": "친구,이성",
    "content": "외모에 대한 놀림이 있어 자존감이 떨어졌습니다. (사례 #44)",
    "createdAt": "2025.01.07",
    "recommends": 22,
    "reports": 10,
    "comments": 26,
    "severity": 2,
    "mindState": 3,
    "staeScore": 91,
    "sendLifeMessages": true
  },
  {
    "id": 45,
    "classification": "외모문제",
    "content": "최근 학교에서 스트레스를 많이 받아 힘듭니다. (사례 #45)",
    "createdAt": "2025.08.08",
    "recommends": 60,
    "reports": 7,
    "comments": 12,
    "severity": 4,
    "mindState": 3,
    "staeScore": 166,
    "sendLifeMessages": true
  },
  {
    "id": 46,
    "classification": "부모갈등",
    "content": "최근 학교에서 스트레스를 많이 받아 힘듭니다. (사례 #46)",
    "createdAt": "2025.06.18",
    "recommends": 24,
    "reports": 12,
    "comments": 21,
    "severity": 3,
    "mindState": 1,
    "staeScore": 405,
    "sendLifeMessages": false
  },
  {
    "id": 47,
    "classification": "가정형편,경제",
    "content": "힘든 시기를 이겨냈던 경험을 나누고 싶습니다. (사례 #47)",
    "createdAt": "2025.04.13",
    "recommends": 86,
    "reports": 10,
    "comments": 1,
    "severity": 1,
    "mindState": 3,
    "staeScore": 101,
    "sendLifeMessages": false
  },
  {
    "id": 48,
    "classification": "왕따,학폭",
    "content": "수학 점수가 잘 오르지 않아 걱정이에요. (사례 #48)",
    "createdAt": "2025.06.02",
    "recommends": 55,
    "reports": 11,
    "comments": 20,
    "severity": 4,
    "mindState": 5,
    "staeScore": 271,
    "sendLifeMessages": true
  },
  {
    "id": 49,
    "classification": "외모문제",
    "content": "어떤 선택을 해야 할지 조언이 필요합니다. (사례 #49)",
    "createdAt": "2025.02.18",
    "recommends": 32,
    "reports": 1,
    "comments": 45,
    "severity": 4,
    "mindState": 1,
    "staeScore": 276,
    "sendLifeMessages": true
  },
  {
    "id": 50,
    "classification": "가정형편,경제",
    "content": "외모에 대한 놀림이 있어 자존감이 떨어졌습니다. (사례 #50)",
    "createdAt": "2025.01.18",
    "recommends": 85,
    "reports": 10,
    "comments": 39,
    "severity": 3,
    "mindState": 1,
    "staeScore": 378,
    "sendLifeMessages": false
  }
];