export const lifeMessageMock = [
  {
    id: 1,
    classification: '부모갈등',
    isAllow: '승인대기',
    religion: '상관없음',
    title: '살아있다는 건',
    file: '240805.m4a',
    date: '2025.01.26',
    nickName: '하늘소녀(메뚜기)',
    reports: 0,
    comments: 3,
    lifeSaves: 0,
    courage: 10,
    notHelpFul: 1,
    sending: 5,
    approver: '관리자3'
  },
  {
    id: 2,
    classification: '성적,학업',
    isAllow: '승인대기',
    religion: '상관없음',
    title: '희망을 잃지 마세요',
    file: '240802.m4a',
    date: '2025.01.31',
    nickName: '하늘소녀(메뚜기)',
    reports: 2,
    comments: 1,
    lifeSaves: 10,
    courage: 2,
    notHelpFul: 4,
    sending: 19,
    approver: '관리자3'
  },
  {
    id: 3,
    classification: '외모문제',
    isAllow: '거절',
    religion: '무교',
    title: '당신은 혼자가 아니에요',
    file: '240802.m4a',
    date: '2025.02.18',
    nickName: '슬픈소년(메뚜기)',
    reports: 3,
    comments: 5,
    lifeSaves: 8,
    courage: 4,
    notHelpFul: 2,
    sending: 15,
    approver: '관리자2'
  },
  {
    id: 4,
    classification: '선생갈등',
    isAllow: '승인보류',
    religion: '기독교',
    title: '당신은 혼자가 아니에요',
    file: '240803.m4a',
    date: '2025.01.25',
    nickName: '멋쟁이(메뚜기)',
    reports: 2,
    comments: 3,
    lifeSaves: 4,
    courage: 1,
    notHelpFul: 0,
    sending: 2,
    approver: '관리자1'
  },
  {
    id: 5,
    classification: '왕따,학폭',
    isAllow: '승인완료',
    religion: '불교',
    title: '기억해줘요',
    file: '240801.m4a',
    date: '2025.02.23',
    nickName: '이정현(메뚜기)',
    reports: 1,
    comments: 1,
    lifeSaves: 1,
    courage: 5,
    notHelpFul: 1,
    sending: 10,
    approver: '관리자3'
  },
  {
    id: 6,
    classification: '외모문제',
    isAllow: '거절',
    religion: '무교',
    title: '당신은 혼자가 아니에요',
    file: '240802.m4a',
    date: '2025.02.20',
    nickName: '혜람이(메뚜기)',
    reports: 3,
    comments: 4,
    lifeSaves: 9,
    courage: 8,
    notHelpFul: 5,
    sending: 18,
    approver: '관리자3'
  },
  {
    id: 7,
    classification: '부모갈등',
    isAllow: '거절',
    religion: '무교',
    title: '그래도 괜찮아요',
    file: '240803.m4a',
    date: '2025.01.14',
    nickName: '해피곰(메뚜기)',
    reports: 1,
    comments: 1,
    lifeSaves: 10,
    courage: 0,
    notHelpFul: 0,
    sending: 2,
    approver: '관리자3'
  },
  {
    id: 8,
    classification: '성적,학업',
    isAllow: '거절',
    religion: '불교',
    title: '살아있다는 건',
    file: '240801.m4a',
    date: '2025.02.26',
    nickName: '하늘소녀(메뚜기)',
    reports: 0,
    comments: 5,
    lifeSaves: 7,
    courage: 7,
    notHelpFul: 3,
    sending: 5,
    approver: '관리자3'
  },
  {
    id: 9,
    classification: '부모갈등',
    isAllow: '승인보류',
    religion: '무교',
    title: '당신은 혼자가 아니에요',
    file: '240802.m4a',
    date: '2025.02.27',
    nickName: '추동훈(메뚜기)',
    reports: 1,
    comments: 5,
    lifeSaves: 3,
    courage: 1,
    notHelpFul: 5,
    sending: 18,
    approver: '관리자2'
  },
  {
    id: 10,
    classification: '선생갈등',
    isAllow: '승인대기',
    religion: '불교',
    title: '희망을 잃지 마세요',
    file: '240803.m4a',
    date: '2025.01.21',
    nickName: '혜람이(메뚜기)',
    reports: 1,
    comments: 3,
    lifeSaves: 10,
    courage: 8,
    notHelpFul: 5,
    sending: 17,
    approver: '관리자1'
  },
  {
    id: 11,
    classification: '부모갈등',
    isAllow: '승인보류',
    religion: '기독교',
    title: '기억해줘요',
    file: '240803.m4a',
    date: '2025.01.08',
    nickName: '해피곰(메뚜기)',
    reports: 0,
    comments: 4,
    lifeSaves: 5,
    courage: 7,
    notHelpFul: 2,
    sending: 9,
    approver: '관리자3'
  },
  {
    id: 12,
    classification: '공통',
    isAllow: '승인보류',
    religion: '상관없음',
    title: '그래도 괜찮아요',
    file: '240801.m4a',
    date: '2025.01.12',
    nickName: '멋쟁이(메뚜기)',
    reports: 3,
    comments: 4,
    lifeSaves: 6,
    courage: 8,
    notHelpFul: 1,
    sending: 4,
    approver: '관리자2'
  },
  {
    id: 13,
    classification: '부모갈등',
    isAllow: '거절',
    religion: '무교',
    title: '당신은 혼자가 아니에요',
    file: '240803.m4a',
    date: '2025.01.18',
    nickName: '추동훈(메뚜기)',
    reports: 0,
    comments: 5,
    lifeSaves: 8,
    courage: 3,
    notHelpFul: 1,
    sending: 10,
    approver: '관리자3'
  },
  {
    id: 14,
    classification: '친구,이성',
    isAllow: '승인완료',
    religion: '불교',
    title: '당신은 혼자가 아니에요',
    file: '240803.m4a',
    date: '2025.02.09',
    nickName: '해피곰(메뚜기)',
    reports: 0,
    comments: 0,
    lifeSaves: 8,
    courage: 10,
    notHelpFul: 2,
    sending: 2,
    approver: '관리자3'
  },
  {
    id: 15,
    classification: '부모갈등',
    isAllow: '승인대기',
    religion: '상관없음',
    title: '당신은 혼자가 아니에요',
    file: '240802.m4a',
    date: '2025.02.07',
    nickName: '슬픈소년(메뚜기)',
    reports: 2,
    comments: 2,
    lifeSaves: 1,
    courage: 6,
    notHelpFul: 2,
    sending: 20,
    approver: '관리자3'
  },
  {
    id: 16,
    classification: '왕따,학폭',
    isAllow: '승인완료',
    religion: '상관없음',
    title: '희망을 잃지 마세요',
    file: '240802.m4a',
    date: '2025.02.26',
    nickName: '혜람이(메뚜기)',
    reports: 1,
    comments: 0,
    lifeSaves: 10,
    courage: 10,
    notHelpFul: 0,
    sending: 17,
    approver: '관리자1'
  },
  {
    id: 17,
    classification: '친구,이성',
    isAllow: '승인완료',
    religion: '무교',
    title: '희망을 잃지 마세요',
    file: '240805.m4a',
    date: '2025.01.20',
    nickName: '혜람이(메뚜기)',
    reports: 1,
    comments: 4,
    lifeSaves: 3,
    courage: 9,
    notHelpFul: 3,
    sending: 3,
    approver: '관리자2'
  },
  {
    id: 18,
    classification: '공통',
    isAllow: '승인대기',
    religion: '무교',
    title: '기억해줘요',
    file: '240804.m4a',
    date: '2025.02.23',
    nickName: '김나라(메뚜기)',
    reports: 3,
    comments: 3,
    lifeSaves: 10,
    courage: 10,
    notHelpFul: 1,
    sending: 13,
    approver: '관리자2'
  },
  {
    id: 19,
    classification: '선생갈등',
    isAllow: '승인대기',
    religion: '상관없음',
    title: '그래도 괜찮아요',
    file: '240801.m4a',
    date: '2025.01.27',
    nickName: '슬픈소년(메뚜기)',
    reports: 1,
    comments: 2,
    lifeSaves: 6,
    courage: 6,
    notHelpFul: 3,
    sending: 14,
    approver: '관리자1'
  },
  {
    id: 20,
    classification: '친구,이성',
    isAllow: '거절',
    religion: '상관없음',
    title: '그래도 괜찮아요',
    file: '240803.m4a',
    date: '2025.02.11',
    nickName: '해피곰(메뚜기)',
    reports: 3,
    comments: 2,
    lifeSaves: 7,
    courage: 7,
    notHelpFul: 4,
    sending: 10,
    approver: '관리자1'
  },
  {
    id: 21,
    classification: '성적,학업',
    isAllow: '승인완료',
    religion: '기독교',
    title: '기억해줘요',
    file: '240801.m4a',
    date: '2025.02.27',
    nickName: '이정현(메뚜기)',
    reports: 1,
    comments: 0,
    lifeSaves: 2,
    courage: 4,
    notHelpFul: 5,
    sending: 16,
    approver: '관리자2'
  },
  {
    id: 22,
    classification: '왕따,학폭',
    isAllow: '승인대기',
    religion: '무교',
    title: '당신은 혼자가 아니에요',
    file: '240804.m4a',
    date: '2025.02.16',
    nickName: '슬픈소년(메뚜기)',
    reports: 1,
    comments: 4,
    lifeSaves: 9,
    courage: 2,
    notHelpFul: 4,
    sending: 9,
    approver: '관리자3'
  },
  {
    id: 23,
    classification: '성적,학업',
    isAllow: '승인완료',
    religion: '무교',
    title: '기억해줘요',
    file: '240803.m4a',
    date: '2025.02.04',
    nickName: '멋쟁이(메뚜기)',
    reports: 2,
    comments: 0,
    lifeSaves: 0,
    courage: 2,
    notHelpFul: 3,
    sending: 16,
    approver: '관리자2'
  },
  {
    id: 24,
    classification: '공통',
    isAllow: '승인완료',
    religion: '기독교',
    title: '당신은 혼자가 아니에요',
    file: '240802.m4a',
    date: '2025.01.16',
    nickName: '혜람이(메뚜기)',
    reports: 0,
    comments: 5,
    lifeSaves: 10,
    courage: 8,
    notHelpFul: 0,
    sending: 4,
    approver: '관리자3'
  },
  {
    id: 25,
    classification: '가정형편,경제',
    isAllow: '승인보류',
    religion: '천주교',
    title: '기억해줘요',
    file: '240803.m4a',
    date: '2025.01.20',
    nickName: '김나라(메뚜기)',
    reports: 0,
    comments: 0,
    lifeSaves: 2,
    courage: 4,
    notHelpFul: 1,
    sending: 16,
    approver: '관리자3'
  },
  {
    id: 26,
    classification: '부모갈등',
    isAllow: '거절',
    religion: '상관없음',
    title: '그래도 괜찮아요',
    file: '240802.m4a',
    date: '2025.01.24',
    nickName: '혜람이(메뚜기)',
    reports: 3,
    comments: 5,
    lifeSaves: 5,
    courage: 1,
    notHelpFul: 4,
    sending: 16,
    approver: '관리자1'
  },
  {
    id: 27,
    classification: '성적,학업',
    isAllow: '승인보류',
    religion: '무교',
    title: '기억해줘요',
    file: '240801.m4a',
    date: '2025.02.23',
    nickName: '이정현(메뚜기)',
    reports: 3,
    comments: 1,
    lifeSaves: 8,
    courage: 6,
    notHelpFul: 3,
    sending: 5,
    approver: '관리자3'
  },
  {
    id: 28,
    classification: '친구,이성',
    isAllow: '승인보류',
    religion: '불교',
    title: '그래도 괜찮아요',
    file: '240804.m4a',
    date: '2025.02.15',
    nickName: '하늘소녀(메뚜기)',
    reports: 3,
    comments: 3,
    lifeSaves: 5,
    courage: 7,
    notHelpFul: 0,
    sending: 10,
    approver: '관리자1'
  },
  {
    id: 29,
    classification: '부모갈등',
    isAllow: '승인대기',
    religion: '기독교',
    title: '당신은 혼자가 아니에요',
    file: '240801.m4a',
    date: '2025.01.15',
    nickName: '추동훈(메뚜기)',
    reports: 0,
    comments: 5,
    lifeSaves: 6,
    courage: 5,
    notHelpFul: 3,
    sending: 19,
    approver: '관리자1'
  },
  {
    id: 30,
    classification: '친구,이성',
    isAllow: '승인보류',
    religion: '무교',
    title: '그래도 괜찮아요',
    file: '240802.m4a',
    date: '2025.01.27',
    nickName: '해피곰(메뚜기)',
    reports: 0,
    comments: 5,
    lifeSaves: 5,
    courage: 4,
    notHelpFul: 4,
    sending: 6,
    approver: '관리자1'
  },
  {
    id: 31,
    classification: '공통',
    isAllow: '승인완료',
    religion: '기독교',
    title: '희망을 잃지 마세요',
    file: '240801.m4a',
    date: '2025.02.06',
    nickName: '슬픈소년(메뚜기)',
    reports: 0,
    comments: 3,
    lifeSaves: 7,
    courage: 2,
    notHelpFul: 1,
    sending: 13,
    approver: '관리자3'
  },
  {
    id: 32,
    classification: '왕따,학폭',
    isAllow: '거절',
    religion: '천주교',
    title: '기억해줘요',
    file: '240803.m4a',
    date: '2025.02.14',
    nickName: '추동훈(메뚜기)',
    reports: 1,
    comments: 1,
    lifeSaves: 9,
    courage: 7,
    notHelpFul: 2,
    sending: 12,
    approver: '관리자2'
  },
  {
    id: 33,
    classification: '친구,이성',
    isAllow: '승인완료',
    religion: '불교',
    title: '희망을 잃지 마세요',
    file: '240804.m4a',
    date: '2025.03.02',
    nickName: '해피곰(메뚜기)',
    reports: 0,
    comments: 4,
    lifeSaves: 10,
    courage: 0,
    notHelpFul: 1,
    sending: 8,
    approver: '관리자2'
  },
  {
    id: 34,
    classification: '친구,이성',
    isAllow: '거절',
    religion: '상관없음',
    title: '당신은 혼자가 아니에요',
    file: '240804.m4a',
    date: '2025.02.24',
    nickName: '혜람이(메뚜기)',
    reports: 0,
    comments: 3,
    lifeSaves: 3,
    courage: 7,
    notHelpFul: 3,
    sending: 1,
    approver: '관리자2'
  },
  {
    id: 35,
    classification: '외모문제',
    isAllow: '승인보류',
    religion: '무교',
    title: '희망을 잃지 마세요',
    file: '240803.m4a',
    date: '2025.01.14',
    nickName: '이정현(메뚜기)',
    reports: 3,
    comments: 3,
    lifeSaves: 7,
    courage: 3,
    notHelpFul: 2,
    sending: 13,
    approver: '관리자2'
  },
  {
    id: 36,
    classification: '가정형편,경제',
    isAllow: '거절',
    religion: '불교',
    title: '그래도 괜찮아요',
    file: '240803.m4a',
    date: '2025.01.29',
    nickName: '멋쟁이(메뚜기)',
    reports: 0,
    comments: 1,
    lifeSaves: 7,
    courage: 4,
    notHelpFul: 4,
    sending: 19,
    approver: '관리자2'
  },
  {
    id: 37,
    classification: '친구,이성',
    isAllow: '승인보류',
    religion: '기독교',
    title: '당신은 혼자가 아니에요',
    file: '240802.m4a',
    date: '2025.01.29',
    nickName: '추동훈(메뚜기)',
    reports: 1,
    comments: 3,
    lifeSaves: 1,
    courage: 10,
    notHelpFul: 5,
    sending: 11,
    approver: '관리자1'
  },
  {
    id: 38,
    classification: '가정형편,경제',
    isAllow: '승인완료',
    religion: '무교',
    title: '살아있다는 건',
    file: '240804.m4a',
    date: '2025.02.09',
    nickName: '슬픈소년(메뚜기)',
    reports: 3,
    comments: 0,
    lifeSaves: 2,
    courage: 2,
    notHelpFul: 0,
    sending: 19,
    approver: '관리자1'
  },
  {
    id: 39,
    classification: '선생갈등',
    isAllow: '승인완료',
    religion: '천주교',
    title: '그래도 괜찮아요',
    file: '240801.m4a',
    date: '2025.02.23',
    nickName: '이정현(메뚜기)',
    reports: 3,
    comments: 2,
    lifeSaves: 9,
    courage: 3,
    notHelpFul: 2,
    sending: 19,
    approver: '관리자3'
  },
  {
    id: 40,
    classification: '왕따,학폭',
    isAllow: '승인보류',
    religion: '불교',
    title: '그래도 괜찮아요',
    file: '240804.m4a',
    date: '2025.02.10',
    nickName: '혜람이(메뚜기)',
    reports: 2,
    comments: 5,
    lifeSaves: 5,
    courage: 1,
    notHelpFul: 3,
    sending: 7,
    approver: '관리자3'
  },
  {
    id: 41,
    classification: '친구,이성',
    isAllow: '승인보류',
    religion: '불교',
    title: '희망을 잃지 마세요',
    file: '240803.m4a',
    date: '2025.02.01',
    nickName: '슬픈소년(메뚜기)',
    reports: 1,
    comments: 4,
    lifeSaves: 8,
    courage: 2,
    notHelpFul: 1,
    sending: 14,
    approver: '관리자1'
  },
  {
    id: 42,
    classification: '왕따,학폭',
    isAllow: '거절',
    religion: '무교',
    title: '희망을 잃지 마세요',
    file: '240801.m4a',
    date: '2025.01.04',
    nickName: '슬픈소년(메뚜기)',
    reports: 3,
    comments: 3,
    lifeSaves: 1,
    courage: 4,
    notHelpFul: 5,
    sending: 20,
    approver: '관리자2'
  },
  {
    id: 43,
    classification: '공통',
    isAllow: '거절',
    religion: '불교',
    title: '희망을 잃지 마세요',
    file: '240801.m4a',
    date: '2025.02.20',
    nickName: '해피곰(메뚜기)',
    reports: 3,
    comments: 3,
    lifeSaves: 3,
    courage: 2,
    notHelpFul: 0,
    sending: 13,
    approver: '관리자3'
  },
  {
    id: 44,
    classification: '외모문제',
    isAllow: '승인보류',
    religion: '무교',
    title: '기억해줘요',
    file: '240801.m4a',
    date: '2025.01.21',
    nickName: '멋쟁이(메뚜기)',
    reports: 1,
    comments: 2,
    lifeSaves: 4,
    courage: 5,
    notHelpFul: 0,
    sending: 18,
    approver: '관리자3'
  },
  {
    id: 45,
    classification: '선생갈등',
    isAllow: '거절',
    religion: '상관없음',
    title: '그래도 괜찮아요',
    file: '240804.m4a',
    date: '2025.01.08',
    nickName: '슬픈소년(메뚜기)',
    reports: 2,
    comments: 3,
    lifeSaves: 3,
    courage: 3,
    notHelpFul: 5,
    sending: 4,
    approver: '관리자1'
  },
  {
    id: 46,
    classification: '왕따,학폭',
    isAllow: '거절',
    religion: '기독교',
    title: '살아있다는 건',
    file: '240805.m4a',
    date: '2025.02.19',
    nickName: '김나라(메뚜기)',
    reports: 0,
    comments: 0,
    lifeSaves: 0,
    courage: 8,
    notHelpFul: 2,
    sending: 1,
    approver: '관리자3'
  },
  {
    id: 47,
    classification: '가정형편,경제',
    isAllow: '승인대기',
    religion: '기독교',
    title: '그래도 괜찮아요',
    file: '240804.m4a',
    date: '2025.02.24',
    nickName: '슬픈소년(메뚜기)',
    reports: 0,
    comments: 5,
    lifeSaves: 2,
    courage: 3,
    notHelpFul: 0,
    sending: 11,
    approver: '관리자1'
  },
  {
    id: 48,
    classification: '외모문제',
    isAllow: '승인완료',
    religion: '불교',
    title: '희망을 잃지 마세요',
    file: '240801.m4a',
    date: '2025.01.03',
    nickName: '멋쟁이(메뚜기)',
    reports: 0,
    comments: 5,
    lifeSaves: 6,
    courage: 8,
    notHelpFul: 5,
    sending: 2,
    approver: '관리자1'
  },
  {
    id: 49,
    classification: '친구,이성',
    isAllow: '거절',
    religion: '무교',
    title: '당신은 혼자가 아니에요',
    file: '240802.m4a',
    date: '2025.01.04',
    nickName: '혜람이(메뚜기)',
    reports: 2,
    comments: 3,
    lifeSaves: 10,
    courage: 4,
    notHelpFul: 4,
    sending: 11,
    approver: '관리자3'
  },
  {
    id: 50,
    classification: '외모문제',
    isAllow: '거절',
    religion: '불교',
    title: '살아있다는 건',
    file: '240804.m4a',
    date: '2025.01.31',
    nickName: '해피곰(메뚜기)',
    reports: 1,
    comments: 4,
    lifeSaves: 4,
    courage: 5,
    notHelpFul: 2,
    sending: 14,
    approver: '관리자1'
  },
];