export const reportedPostMock = [
  {
    post_id: 1,
    nickname: "유저1",
    email: "user1@test.com",
    type: "홍보 및 광고",
    status: "처리대기",
    content: "이것은 1번째 게시글 내용입니다.",
    reportedAt: "2025-08-26 12:00:00",
    bannedAt: "",
    totalReportCount: 10,
    spammingCount: 3,
    inappropriateLanguageCount: 2,
    verbalAbuseCount: 5,
    sexualHarassmentCount: 1,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-01 01:58:00",
        likes: 4,
        reports: 1,
        reported: false,
      },
    ],
  },
  {
    post_id: 2,
    nickname: "유저2",
    email: "user2@test.com",
    type: "음담패설",
    status: "자동정지",
    content: "이것은 2번째 게시글 내용입니다.",
    reportedAt: "2025-08-02 12:00:00",
    bannedAt: "2025-09-04 15:00:00",
    totalReportCount: 4,
    spammingCount: 3,
    inappropriateLanguageCount: 4,
    verbalAbuseCount: 4,
    sexualHarassmentCount: 4,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-03 01:16:00",
        likes: 7,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-05 04:13:00",
        likes: 0,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-03 14:49:00",
        likes: 2,
        reports: 1,
        reported: true,
      },
      {
        nickname: "익명4",
        email: "anon4@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-04 06:02:00",
        likes: 6,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명5",
        email: "anon5@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-02 19:19:00",
        likes: 7,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 3,
    nickname: "유저3",
    email: "user3@test.com",
    type: "홍보 및 광고",
    status: "자동정지",
    content: "이것은 3번째 게시글 내용입니다.",
    reportedAt: "2025-08-27 12:00:00",
    bannedAt: "2025-09-03 15:00:00",
    totalReportCount: 20,
    spammingCount: 5,
    inappropriateLanguageCount: 1,
    verbalAbuseCount: 5,
    sexualHarassmentCount: 2,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-01 23:18:00",
        likes: 9,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-01 10:04:00",
        likes: 5,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-02 12:15:00",
        likes: 8,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명4",
        email: "anon4@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-02 22:24:00",
        likes: 0,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명5",
        email: "anon5@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-02 20:49:00",
        likes: 3,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 4,
    nickname: "유저4",
    email: "user4@test.com",
    type: "도배",
    status: "처리대기",
    content: "이것은 4번째 게시글 내용입니다.",
    reportedAt: "2025-08-28 12:00:00",
    bannedAt: "",
    totalReportCount: 15,
    spammingCount: 1,
    inappropriateLanguageCount: 3,
    verbalAbuseCount: 3,
    sexualHarassmentCount: 3,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-02 17:21:00",
        likes: 5,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-03 04:21:00",
        likes: 1,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-01 02:05:00",
        likes: 8,
        reports: 0,
        reported: true,
      },
    ],
  },
  {
    post_id: 5,
    nickname: "유저5",
    email: "user5@test.com",
    type: "욕설 비방",
    status: "자동정지",
    content: "이것은 5번째 게시글 내용입니다.",
    reportedAt: "2025-08-05 12:00:00",
    bannedAt: "2025-09-05 15:00:00",
    totalReportCount: 2,
    spammingCount: 0,
    inappropriateLanguageCount: 0,
    verbalAbuseCount: 5,
    sexualHarassmentCount: 4,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-04 09:20:00",
        likes: 10,
        reports: 1,
        reported: true,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-04 09:01:00",
        likes: 0,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-01 03:57:00",
        likes: 0,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명4",
        email: "anon4@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-04 14:21:00",
        likes: 6,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명5",
        email: "anon5@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-04 04:52:00",
        likes: 6,
        reports: 2,
        reported: true,
      },
    ],
  },
  {
    post_id: 6,
    nickname: "유저6",
    email: "user6@test.com",
    type: "홍보 및 광고",
    status: "처리대기",
    content: "이것은 6번째 게시글 내용입니다.",
    reportedAt: "2025-08-21 12:00:00",
    bannedAt: "2025-09-03 15:00:00",
    totalReportCount: 5,
    spammingCount: 0,
    inappropriateLanguageCount: 2,
    verbalAbuseCount: 1,
    sexualHarassmentCount: 2,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-03 03:28:00",
        likes: 7,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-04 20:34:00",
        likes: 6,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-01 09:02:00",
        likes: 4,
        reports: 1,
        reported: true,
      },
      {
        nickname: "익명4",
        email: "anon4@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-02 03:34:00",
        likes: 6,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명5",
        email: "anon5@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-04 21:36:00",
        likes: 0,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 7,
    nickname: "유저7",
    email: "user7@test.com",
    type: "도배",
    status: "자동정지",
    content: "이것은 7번째 게시글 내용입니다.",
    reportedAt: "2025-08-26 12:00:00",
    bannedAt: "",
    totalReportCount: 20,
    spammingCount: 3,
    inappropriateLanguageCount: 0,
    verbalAbuseCount: 4,
    sexualHarassmentCount: 3,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-02 23:38:00",
        likes: 9,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-05 05:50:00",
        likes: 7,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-05 10:54:00",
        likes: 2,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 8,
    nickname: "유저8",
    email: "user8@test.com",
    type: "홍보 및 광고",
    status: "처리대기",
    content: "이것은 8번째 게시글 내용입니다.",
    reportedAt: "2025-08-17 12:00:00",
    bannedAt: "2025-09-01 15:00:00",
    totalReportCount: 17,
    spammingCount: 4,
    inappropriateLanguageCount: 4,
    verbalAbuseCount: 2,
    sexualHarassmentCount: 3,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-02 10:24:00",
        likes: 3,
        reports: 0,
        reported: true,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-05 18:06:00",
        likes: 7,
        reports: 1,
        reported: false,
      },
    ],
  },
  {
    post_id: 9,
    nickname: "유저9",
    email: "user9@test.com",
    type: "홍보 및 광고",
    status: "처리대기",
    content: "이것은 9번째 게시글 내용입니다.",
    reportedAt: "2025-08-19 12:00:00",
    bannedAt: "2025-09-02 15:00:00",
    totalReportCount: 6,
    spammingCount: 1,
    inappropriateLanguageCount: 3,
    verbalAbuseCount: 2,
    sexualHarassmentCount: 4,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-05 20:25:00",
        likes: 1,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-01 17:41:00",
        likes: 0,
        reports: 0,
        reported: true,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-02 01:57:00",
        likes: 3,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명4",
        email: "anon4@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-04 05:42:00",
        likes: 1,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명5",
        email: "anon5@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-02 12:49:00",
        likes: 7,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 10,
    nickname: "유저10",
    email: "user10@test.com",
    type: "홍보 및 광고",
    status: "자동정지",
    content: "이것은 10번째 게시글 내용입니다.",
    reportedAt: "2025-08-06 12:00:00",
    bannedAt: "",
    totalReportCount: 6,
    spammingCount: 0,
    inappropriateLanguageCount: 2,
    verbalAbuseCount: 2,
    sexualHarassmentCount: 1,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-02 19:42:00",
        likes: 7,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 11,
    nickname: "유저11",
    email: "user11@test.com",
    type: "홍보 및 광고",
    status: "처리대기",
    content: "이것은 11번째 게시글 내용입니다.",
    reportedAt: "2025-08-25 12:00:00",
    bannedAt: "2025-09-04 15:00:00",
    totalReportCount: 17,
    spammingCount: 4,
    inappropriateLanguageCount: 3,
    verbalAbuseCount: 3,
    sexualHarassmentCount: 3,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-01 05:54:00",
        likes: 10,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-05 09:40:00",
        likes: 9,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-02 15:09:00",
        likes: 6,
        reports: 2,
        reported: true,
      },
    ],
  },
  {
    post_id: 12,
    nickname: "유저12",
    email: "user12@test.com",
    type: "홍보 및 광고",
    status: "자동정지",
    content: "이것은 12번째 게시글 내용입니다.",
    reportedAt: "2025-08-22 12:00:00",
    bannedAt: "2025-09-03 15:00:00",
    totalReportCount: 12,
    spammingCount: 3,
    inappropriateLanguageCount: 5,
    verbalAbuseCount: 5,
    sexualHarassmentCount: 3,
    comments: [],
  },
  {
    post_id: 13,
    nickname: "유저13",
    email: "user13@test.com",
    type: "욕설 비방",
    status: "자동정지",
    content: "이것은 13번째 게시글 내용입니다.",
    reportedAt: "2025-08-26 12:00:00",
    bannedAt: "",
    totalReportCount: 20,
    spammingCount: 3,
    inappropriateLanguageCount: 3,
    verbalAbuseCount: 0,
    sexualHarassmentCount: 2,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-04 07:17:00",
        likes: 5,
        reports: 2,
        reported: false,
      },
    ],
  },
  {
    post_id: 14,
    nickname: "유저14",
    email: "user14@test.com",
    type: "도배",
    status: "처리대기",
    content: "이것은 14번째 게시글 내용입니다.",
    reportedAt: "2025-08-08 12:00:00",
    bannedAt: "2025-09-05 15:00:00",
    totalReportCount: 4,
    spammingCount: 0,
    inappropriateLanguageCount: 1,
    verbalAbuseCount: 3,
    sexualHarassmentCount: 1,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-05 13:23:00",
        likes: 2,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-02 12:57:00",
        likes: 9,
        reports: 2,
        reported: false,
      },
    ],
  },
  {
    post_id: 15,
    nickname: "유저15",
    email: "user15@test.com",
    type: "도배",
    status: "자동정지",
    content: "이것은 15번째 게시글 내용입니다.",
    reportedAt: "2025-08-25 12:00:00",
    bannedAt: "2025-09-03 15:00:00",
    totalReportCount: 17,
    spammingCount: 3,
    inappropriateLanguageCount: 3,
    verbalAbuseCount: 0,
    sexualHarassmentCount: 4,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-01 22:42:00",
        likes: 9,
        reports: 2,
        reported: false,
      },
    ],
  },
  {
    post_id: 16,
    nickname: "유저16",
    email: "user16@test.com",
    type: "도배",
    status: "자동정지",
    content: "이것은 16번째 게시글 내용입니다.",
    reportedAt: "2025-08-24 12:00:00",
    bannedAt: "",
    totalReportCount: 1,
    spammingCount: 0,
    inappropriateLanguageCount: 3,
    verbalAbuseCount: 0,
    sexualHarassmentCount: 3,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-01 12:37:00",
        likes: 8,
        reports: 1,
        reported: true,
      },
    ],
  },
  {
    post_id: 17,
    nickname: "유저17",
    email: "user17@test.com",
    type: "욕설 비방",
    status: "자동정지",
    content: "이것은 17번째 게시글 내용입니다.",
    reportedAt: "2025-08-12 12:00:00",
    bannedAt: "2025-09-04 15:00:00",
    totalReportCount: 9,
    spammingCount: 3,
    inappropriateLanguageCount: 4,
    verbalAbuseCount: 2,
    sexualHarassmentCount: 1,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-01 09:07:00",
        likes: 9,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-05 10:08:00",
        likes: 10,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 18,
    nickname: "유저18",
    email: "user18@test.com",
    type: "홍보 및 광고",
    status: "자동정지",
    content: "이것은 18번째 게시글 내용입니다.",
    reportedAt: "2025-08-05 12:00:00",
    bannedAt: "2025-09-04 15:00:00",
    totalReportCount: 15,
    spammingCount: 0,
    inappropriateLanguageCount: 1,
    verbalAbuseCount: 1,
    sexualHarassmentCount: 0,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-03 17:28:00",
        likes: 7,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-03 18:24:00",
        likes: 1,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-02 00:47:00",
        likes: 6,
        reports: 1,
        reported: false,
      },
    ],
  },
  {
    post_id: 19,
    nickname: "유저19",
    email: "user19@test.com",
    type: "도배",
    status: "처리대기",
    content: "이것은 19번째 게시글 내용입니다.",
    reportedAt: "2025-08-11 12:00:00",
    bannedAt: "",
    totalReportCount: 2,
    spammingCount: 1,
    inappropriateLanguageCount: 0,
    verbalAbuseCount: 3,
    sexualHarassmentCount: 2,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-01 17:20:00",
        likes: 4,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 20,
    nickname: "유저20",
    email: "user20@test.com",
    type: "음담패설",
    status: "처리대기",
    content: "이것은 20번째 게시글 내용입니다.",
    reportedAt: "2025-08-14 12:00:00",
    bannedAt: "2025-09-01 15:00:00",
    totalReportCount: 7,
    spammingCount: 0,
    inappropriateLanguageCount: 2,
    verbalAbuseCount: 3,
    sexualHarassmentCount: 5,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-01 15:08:00",
        likes: 9,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-04 09:10:00",
        likes: 6,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-03 22:07:00",
        likes: 10,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 21,
    nickname: "유저21",
    email: "user21@test.com",
    type: "음담패설",
    status: "자동정지",
    content: "이것은 21번째 게시글 내용입니다.",
    reportedAt: "2025-08-12 12:00:00",
    bannedAt: "2025-09-01 15:00:00",
    totalReportCount: 15,
    spammingCount: 4,
    inappropriateLanguageCount: 3,
    verbalAbuseCount: 2,
    sexualHarassmentCount: 4,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-01 01:15:00",
        likes: 0,
        reports: 1,
        reported: true,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-04 14:47:00",
        likes: 5,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-03 20:17:00",
        likes: 7,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 22,
    nickname: "유저22",
    email: "user22@test.com",
    type: "홍보 및 광고",
    status: "자동정지",
    content: "이것은 22번째 게시글 내용입니다.",
    reportedAt: "2025-08-21 12:00:00",
    bannedAt: "",
    totalReportCount: 13,
    spammingCount: 4,
    inappropriateLanguageCount: 2,
    verbalAbuseCount: 1,
    sexualHarassmentCount: 2,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-04 07:54:00",
        likes: 5,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-02 01:04:00",
        likes: 2,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-05 09:50:00",
        likes: 5,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 23,
    nickname: "유저23",
    email: "user23@test.com",
    type: "도배",
    status: "자동정지",
    content: "이것은 23번째 게시글 내용입니다.",
    reportedAt: "2025-08-26 12:00:00",
    bannedAt: "2025-09-04 15:00:00",
    totalReportCount: 3,
    spammingCount: 5,
    inappropriateLanguageCount: 5,
    verbalAbuseCount: 5,
    sexualHarassmentCount: 1,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-04 02:01:00",
        likes: 4,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-04 11:44:00",
        likes: 1,
        reports: 1,
        reported: true,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-02 22:48:00",
        likes: 9,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 24,
    nickname: "유저24",
    email: "user24@test.com",
    type: "도배",
    status: "자동정지",
    content: "이것은 24번째 게시글 내용입니다.",
    reportedAt: "2025-08-14 12:00:00",
    bannedAt: "2025-09-01 15:00:00",
    totalReportCount: 12,
    spammingCount: 4,
    inappropriateLanguageCount: 0,
    verbalAbuseCount: 3,
    sexualHarassmentCount: 3,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-03 08:33:00",
        likes: 1,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-01 11:54:00",
        likes: 6,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-04 08:38:00",
        likes: 0,
        reports: 2,
        reported: false,
      },
    ],
  },
  {
    post_id: 25,
    nickname: "유저25",
    email: "user25@test.com",
    type: "도배",
    status: "처리대기",
    content: "이것은 25번째 게시글 내용입니다.",
    reportedAt: "2025-08-21 12:00:00",
    bannedAt: "",
    totalReportCount: 11,
    spammingCount: 0,
    inappropriateLanguageCount: 3,
    verbalAbuseCount: 3,
    sexualHarassmentCount: 0,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-05 11:16:00",
        likes: 6,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-01 22:36:00",
        likes: 4,
        reports: 1,
        reported: false,
      },
    ],
  },
  {
    post_id: 26,
    nickname: "유저26",
    email: "user26@test.com",
    type: "음담패설",
    status: "처리대기",
    content: "이것은 26번째 게시글 내용입니다.",
    reportedAt: "2025-08-16 12:00:00",
    bannedAt: "2025-09-02 15:00:00",
    totalReportCount: 6,
    spammingCount: 4,
    inappropriateLanguageCount: 1,
    verbalAbuseCount: 1,
    sexualHarassmentCount: 0,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-01 09:17:00",
        likes: 7,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-05 20:53:00",
        likes: 1,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-03 15:07:00",
        likes: 1,
        reports: 1,
        reported: false,
      },
    ],
  },
  {
    post_id: 27,
    nickname: "유저27",
    email: "user27@test.com",
    type: "홍보 및 광고",
    status: "자동정지",
    content: "이것은 27번째 게시글 내용입니다.",
    reportedAt: "2025-08-26 12:00:00",
    bannedAt: "2025-09-02 15:00:00",
    totalReportCount: 5,
    spammingCount: 0,
    inappropriateLanguageCount: 2,
    verbalAbuseCount: 5,
    sexualHarassmentCount: 2,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-02 19:33:00",
        likes: 9,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 28,
    nickname: "유저28",
    email: "user28@test.com",
    type: "욕설 비방",
    status: "처리대기",
    content: "이것은 28번째 게시글 내용입니다.",
    reportedAt: "2025-08-11 12:00:00",
    bannedAt: "",
    totalReportCount: 16,
    spammingCount: 4,
    inappropriateLanguageCount: 4,
    verbalAbuseCount: 5,
    sexualHarassmentCount: 2,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-05 10:34:00",
        likes: 0,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-02 04:47:00",
        likes: 4,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-02 04:02:00",
        likes: 7,
        reports: 0,
        reported: true,
      },
      {
        nickname: "익명4",
        email: "anon4@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-02 00:19:00",
        likes: 8,
        reports: 0,
        reported: true,
      },
    ],
  },
  {
    post_id: 29,
    nickname: "유저29",
    email: "user29@test.com",
    type: "음담패설",
    status: "처리대기",
    content: "이것은 29번째 게시글 내용입니다.",
    reportedAt: "2025-08-04 12:00:00",
    bannedAt: "2025-09-01 15:00:00",
    totalReportCount: 5,
    spammingCount: 2,
    inappropriateLanguageCount: 5,
    verbalAbuseCount: 0,
    sexualHarassmentCount: 3,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-04 19:50:00",
        likes: 0,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-02 01:24:00",
        likes: 7,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 30,
    nickname: "유저30",
    email: "user30@test.com",
    type: "음담패설",
    status: "자동정지",
    content: "이것은 30번째 게시글 내용입니다.",
    reportedAt: "2025-08-19 12:00:00",
    bannedAt: "2025-09-04 15:00:00",
    totalReportCount: 2,
    spammingCount: 5,
    inappropriateLanguageCount: 4,
    verbalAbuseCount: 1,
    sexualHarassmentCount: 3,
    comments: [],
  },
  {
    post_id: 31,
    nickname: "유저31",
    email: "user31@test.com",
    type: "욕설 비방",
    status: "처리대기",
    content: "이것은 31번째 게시글 내용입니다.",
    reportedAt: "2025-08-18 12:00:00",
    bannedAt: "",
    totalReportCount: 11,
    spammingCount: 2,
    inappropriateLanguageCount: 1,
    verbalAbuseCount: 5,
    sexualHarassmentCount: 2,
    comments: [],
  },
  {
    post_id: 32,
    nickname: "유저32",
    email: "user32@test.com",
    type: "음담패설",
    status: "자동정지",
    content: "이것은 32번째 게시글 내용입니다.",
    reportedAt: "2025-08-09 12:00:00",
    bannedAt: "2025-09-05 15:00:00",
    totalReportCount: 3,
    spammingCount: 3,
    inappropriateLanguageCount: 3,
    verbalAbuseCount: 1,
    sexualHarassmentCount: 3,
    comments: [],
  },
  {
    post_id: 33,
    nickname: "유저33",
    email: "user33@test.com",
    type: "음담패설",
    status: "자동정지",
    content: "이것은 33번째 게시글 내용입니다.",
    reportedAt: "2025-08-27 12:00:00",
    bannedAt: "2025-09-02 15:00:00",
    totalReportCount: 2,
    spammingCount: 1,
    inappropriateLanguageCount: 3,
    verbalAbuseCount: 2,
    sexualHarassmentCount: 2,
    comments: [],
  },
  {
    post_id: 34,
    nickname: "유저34",
    email: "user34@test.com",
    type: "욕설 비방",
    status: "자동정지",
    content: "이것은 34번째 게시글 내용입니다.",
    reportedAt: "2025-08-27 12:00:00",
    bannedAt: "",
    totalReportCount: 20,
    spammingCount: 4,
    inappropriateLanguageCount: 0,
    verbalAbuseCount: 1,
    sexualHarassmentCount: 5,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-05 05:36:00",
        likes: 1,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-03 23:12:00",
        likes: 10,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-01 22:33:00",
        likes: 8,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명4",
        email: "anon4@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-02 10:23:00",
        likes: 2,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 35,
    nickname: "유저35",
    email: "user35@test.com",
    type: "욕설 비방",
    status: "처리대기",
    content: "이것은 35번째 게시글 내용입니다.",
    reportedAt: "2025-08-14 12:00:00",
    bannedAt: "2025-09-04 15:00:00",
    totalReportCount: 6,
    spammingCount: 1,
    inappropriateLanguageCount: 1,
    verbalAbuseCount: 4,
    sexualHarassmentCount: 5,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-05 13:54:00",
        likes: 2,
        reports: 1,
        reported: false,
      },
    ],
  },
  {
    post_id: 36,
    nickname: "유저36",
    email: "user36@test.com",
    type: "음담패설",
    status: "자동정지",
    content: "이것은 36번째 게시글 내용입니다.",
    reportedAt: "2025-08-21 12:00:00",
    bannedAt: "2025-09-05 15:00:00",
    totalReportCount: 5,
    spammingCount: 0,
    inappropriateLanguageCount: 1,
    verbalAbuseCount: 3,
    sexualHarassmentCount: 1,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-01 03:49:00",
        likes: 7,
        reports: 0,
        reported: true,
      },
    ],
  },
  {
    post_id: 37,
    nickname: "유저37",
    email: "user37@test.com",
    type: "홍보 및 광고",
    status: "처리대기",
    content: "이것은 37번째 게시글 내용입니다.",
    reportedAt: "2025-08-15 12:00:00",
    bannedAt: "",
    totalReportCount: 10,
    spammingCount: 3,
    inappropriateLanguageCount: 1,
    verbalAbuseCount: 4,
    sexualHarassmentCount: 0,
    comments: [],
  },
  {
    post_id: 38,
    nickname: "유저38",
    email: "user38@test.com",
    type: "홍보 및 광고",
    status: "처리대기",
    content: "이것은 38번째 게시글 내용입니다.",
    reportedAt: "2025-08-06 12:00:00",
    bannedAt: "2025-09-04 15:00:00",
    totalReportCount: 18,
    spammingCount: 1,
    inappropriateLanguageCount: 3,
    verbalAbuseCount: 4,
    sexualHarassmentCount: 0,
    comments: [],
  },
  {
    post_id: 39,
    nickname: "유저39",
    email: "user39@test.com",
    type: "도배",
    status: "자동정지",
    content: "이것은 39번째 게시글 내용입니다.",
    reportedAt: "2025-08-11 12:00:00",
    bannedAt: "2025-09-02 15:00:00",
    totalReportCount: 17,
    spammingCount: 0,
    inappropriateLanguageCount: 2,
    verbalAbuseCount: 2,
    sexualHarassmentCount: 3,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-03 02:23:00",
        likes: 9,
        reports: 1,
        reported: true,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-04 22:12:00",
        likes: 2,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 40,
    nickname: "유저40",
    email: "user40@test.com",
    type: "음담패설",
    status: "자동정지",
    content: "이것은 40번째 게시글 내용입니다.",
    reportedAt: "2025-08-17 12:00:00",
    bannedAt: "",
    totalReportCount: 18,
    spammingCount: 4,
    inappropriateLanguageCount: 0,
    verbalAbuseCount: 5,
    sexualHarassmentCount: 0,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-04 23:43:00",
        likes: 1,
        reports: 1,
        reported: true,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-05 23:33:00",
        likes: 1,
        reports: 2,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-03 07:25:00",
        likes: 9,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명4",
        email: "anon4@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-04 00:17:00",
        likes: 3,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 41,
    nickname: "유저41",
    email: "user41@test.com",
    type: "도배",
    status: "처리대기",
    content: "이것은 41번째 게시글 내용입니다.",
    reportedAt: "2025-08-08 12:00:00",
    bannedAt: "2025-09-02 15:00:00",
    totalReportCount: 1,
    spammingCount: 4,
    inappropriateLanguageCount: 0,
    verbalAbuseCount: 1,
    sexualHarassmentCount: 2,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-03 22:31:00",
        likes: 5,
        reports: 0,
        reported: true,
      },
    ],
  },
  {
    post_id: 42,
    nickname: "유저42",
    email: "user42@test.com",
    type: "도배",
    status: "자동정지",
    content: "이것은 42번째 게시글 내용입니다.",
    reportedAt: "2025-08-25 12:00:00",
    bannedAt: "2025-09-04 15:00:00",
    totalReportCount: 13,
    spammingCount: 2,
    inappropriateLanguageCount: 4,
    verbalAbuseCount: 1,
    sexualHarassmentCount: 2,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-05 11:42:00",
        likes: 9,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 43,
    nickname: "유저43",
    email: "user43@test.com",
    type: "음담패설",
    status: "처리대기",
    content: "이것은 43번째 게시글 내용입니다.",
    reportedAt: "2025-08-18 12:00:00",
    bannedAt: "",
    totalReportCount: 8,
    spammingCount: 2,
    inappropriateLanguageCount: 1,
    verbalAbuseCount: 1,
    sexualHarassmentCount: 2,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-05 01:29:00",
        likes: 10,
        reports: 0,
        reported: true,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-04 08:24:00",
        likes: 5,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-02 08:20:00",
        likes: 10,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명4",
        email: "anon4@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-02 07:46:00",
        likes: 0,
        reports: 1,
        reported: false,
      },
    ],
  },
  {
    post_id: 44,
    nickname: "유저44",
    email: "user44@test.com",
    type: "욕설 비방",
    status: "처리대기",
    content: "이것은 44번째 게시글 내용입니다.",
    reportedAt: "2025-08-23 12:00:00",
    bannedAt: "2025-09-05 15:00:00",
    totalReportCount: 14,
    spammingCount: 1,
    inappropriateLanguageCount: 2,
    verbalAbuseCount: 3,
    sexualHarassmentCount: 5,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "신고했습니다.",
        createdAt: "2025-09-03 13:27:00",
        likes: 6,
        reports: 0,
        reported: false,
      },
    ],
  },
  {
    post_id: 45,
    nickname: "유저45",
    email: "user45@test.com",
    type: "음담패설",
    status: "처리대기",
    content: "이것은 45번째 게시글 내용입니다.",
    reportedAt: "2025-08-15 12:00:00",
    bannedAt: "2025-09-02 15:00:00",
    totalReportCount: 18,
    spammingCount: 2,
    inappropriateLanguageCount: 3,
    verbalAbuseCount: 5,
    sexualHarassmentCount: 1,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-02 21:36:00",
        likes: 3,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-01 23:22:00",
        likes: 2,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-05 01:46:00",
        likes: 6,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명4",
        email: "anon4@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-02 01:23:00",
        likes: 9,
        reports: 1,
        reported: false,
      },
    ],
  },
  {
    post_id: 46,
    nickname: "유저46",
    email: "user46@test.com",
    type: "욕설 비방",
    status: "처리대기",
    content: "이것은 46번째 게시글 내용입니다.",
    reportedAt: "2025-08-01 12:00:00",
    bannedAt: "",
    totalReportCount: 15,
    spammingCount: 2,
    inappropriateLanguageCount: 0,
    verbalAbuseCount: 5,
    sexualHarassmentCount: 0,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-04 03:37:00",
        likes: 0,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명2",
        email: "anon2@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-04 09:05:00",
        likes: 5,
        reports: 1,
        reported: false,
      },
      {
        nickname: "익명3",
        email: "anon3@test.com",
        content: "관리자 조치 바랍니다.",
        createdAt: "2025-09-02 22:14:00",
        likes: 6,
        reports: 1,
        reported: true,
      },
      {
        nickname: "익명4",
        email: "anon4@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-02 01:31:00",
        likes: 4,
        reports: 0,
        reported: false,
      },
      {
        nickname: "익명5",
        email: "anon5@test.com",
        content: "이건 좀 아닌 것 같아요.",
        createdAt: "2025-09-05 20:42:00",
        likes: 10,
        reports: 0,
        reported: true,
      },
    ],
  },
  {
    post_id: 47,
    nickname: "유저47",
    email: "user47@test.com",
    type: "음담패설",
    status: "처리대기",
    content: "이것은 47번째 게시글 내용입니다.",
    reportedAt: "2025-08-23 12:00:00",
    bannedAt: "2025-09-05 15:00:00",
    totalReportCount: 3,
    spammingCount: 2,
    inappropriateLanguageCount: 1,
    verbalAbuseCount: 0,
    sexualHarassmentCount: 2,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "불쾌한 내용입니다.",
        createdAt: "2025-09-05 11:04:00",
        likes: 1,
        reports: 2,
        reported: false,
      },
    ],
  },
  {
    post_id: 48,
    nickname: "유저48",
    email: "user48@test.com",
    type: "홍보 및 광고",
    status: "자동정지",
    content: "이것은 48번째 게시글 내용입니다.",
    reportedAt: "2025-08-14 12:00:00",
    bannedAt: "2025-09-01 15:00:00",
    totalReportCount: 8,
    spammingCount: 1,
    inappropriateLanguageCount: 2,
    verbalAbuseCount: 0,
    sexualHarassmentCount: 1,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-01 21:12:00",
        likes: 0,
        reports: 1,
        reported: false,
      },
    ],
  },
  {
    post_id: 49,
    nickname: "유저49",
    email: "user49@test.com",
    type: "홍보 및 광고",
    status: "자동정지",
    content: "이것은 49번째 게시글 내용입니다.",
    reportedAt: "2025-08-18 12:00:00",
    bannedAt: "",
    totalReportCount: 12,
    spammingCount: 3,
    inappropriateLanguageCount: 0,
    verbalAbuseCount: 0,
    sexualHarassmentCount: 2,
    comments: [],
  },
  {
    post_id: 50,
    nickname: "유저50",
    email: "user50@test.com",
    type: "홍보 및 광고",
    status: "처리대기",
    content: "이것은 50번째 게시글 내용입니다.",
    reportedAt: "2025-08-18 12:00:00",
    bannedAt: "2025-09-04 15:00:00",
    totalReportCount: 10,
    spammingCount: 2,
    inappropriateLanguageCount: 4,
    verbalAbuseCount: 0,
    sexualHarassmentCount: 2,
    comments: [
      {
        nickname: "익명1",
        email: "anon1@test.com",
        content: "도배는 좀 심하네요.",
        createdAt: "2025-09-01 23:57:00",
        likes: 9,
        reports: 0,
        reported: false,
      },
    ],
  },
];
